"""A published page must not name a record that does not exist (#714).

`check-docs-current` has an orphan check and it works — it caught the stale
`docs/communities/<old-name>.html` the moment a record was renamed in #605:

    ❌ published pages with no record (delete them): Synechococcus_Yarrowia_SPC.html

But it walks `docs/communities/*.html` only. The top-level pages embed record
ids and links too, and nothing looked at them. After that rename,
`community_umap.html` and `community_graph.html` each carried the old id, its
display name, and a link to the page the orphan check had just made me delete —
a dead link on the published site, with every gate green.

Measured on `origin/main` first: both pages were consistent there, so this is a
hole that opens on a rename rather than an existing mess.

**Why those pages are exposed and the per-community ones are not.**
`gen-html` rewrites `docs/communities/` wholesale, so a stale page there is a
leftover file the orphan check can see. The UMAP is built by `just gen-umap`,
which `check-docs-current` deliberately does not run — it needs
`data/embeddings/*.tsv.gz`, a large local artefact absent from CI (#602) — and
`community_graph.html` has **no generator anywhere in the repo**: `grep -rn
community_graph` over the justfile and `src/` returns nothing, and the last
substantive change to it was `f8d85b1`, a hand-edit for exactly this situation.
So neither is regenerated by the gate that would notice.

The check here needs neither generator. Reading which records a page names and
asking whether they exist is pure arithmetic over files already in the tree.

**One direction only.** Every record a page names must exist; NOT every record
must appear on every page. The UMAP legitimately plots 322 of 325 records —
three have no embedding — and asserting the converse would fail on that for no
reason.
"""

from __future__ import annotations

import pathlib
import re

import pytest

REPO = pathlib.Path(__file__).parent.parent
DOCS = REPO / "docs"
COMMUNITIES = REPO / "kb" / "communities"

# `"id": "Some_Record"` in the embedded JSON the UMAP and graph pages carry.
_EMBEDDED_ID = re.compile(r'"id":\s*"([A-Za-z0-9_]+)"')
# `communities/Some_Record.html`, the link form every page uses.
_RECORD_LINK = re.compile(r"communities/([A-Za-z0-9_]+)\.html")


def _records() -> set[str]:
    return {path.stem for path in COMMUNITIES.glob("*.yaml")}


def _pages() -> list[pathlib.Path]:
    """Committed top-level pages.

    Discovered by glob rather than listed, so a page added later is covered
    without anyone remembering to add it -- the "list that cannot notice a new
    member" failure this repository keeps hitting (#635, #471, #630). The
    per-community pages under `docs/communities/` are excluded because
    `check-docs-current` already owns them.
    """
    return sorted(DOCS.glob("*.html"))


def _named_records(page: pathlib.Path) -> set[str]:
    text = page.read_text(encoding="utf-8", errors="replace")
    return set(_EMBEDDED_ID.findall(text)) | set(_RECORD_LINK.findall(text))


def test_the_scan_finds_pages_and_records():
    """A scan that found nothing would make the gate below vacuous."""
    pages = _pages()
    assert len(pages) >= 3, f"expected several published pages, found {[p.name for p in pages]}"
    assert len(_records()) > 300, "the record glob is broken"

    # BOTH patterns, separately. Asserting only the combined total lets one of
    # them rot silently: the pages carry an id and a link for the same record,
    # so link matches alone keep the total high while id staleness stops being
    # checked at all. Found by mutation -- neutering `_EMBEDDED_ID` left this
    # test green.
    text = "\n".join(page.read_text(encoding="utf-8", errors="replace") for page in pages)
    ids, links = _EMBEDDED_ID.findall(text), _RECORD_LINK.findall(text)
    assert len(ids) > 200, (
        f"only {len(ids)} embedded ids matched; `_EMBEDDED_ID` no longer "
        f"matches what the pages contain, so id staleness is unchecked"
    )
    assert len(links) > 500, (
        f"only {len(links)} record links matched; `_RECORD_LINK` no longer "
        f"matches what the pages contain, so dead links are unchecked"
    )


@pytest.mark.parametrize("page", _pages(), ids=lambda p: p.name)
def test_a_published_page_names_only_real_records(page: pathlib.Path):
    """Every record a page names must exist in kb/communities."""
    records = _records()
    dead = sorted(name for name in _named_records(page) if name not in records)
    assert dead == [], (
        f"{page.name} names {len(dead)} record(s) that do not exist, so the "
        f"published site carries dead links and stale entries (#714). Renaming "
        f"or deleting a record means regenerating this page -- `just gen-umap` "
        f"for community_umap.html; community_graph.html has no generator and "
        f"must be edited by hand, as in f8d85b1:\n  " + "\n  ".join(dead)
    )
