"""The denominator report's provenance header must identify the input, not the machine (#479).

`reports/gtdb_denominators.tsv` opens with a line naming the crosswalk it was
built from. That line used to carry `mtime=`, which is a fact about one
filesystem: it differs per machine and per re-download even when the bytes are
identical.

The consequence is not cosmetic. `check-docs-current` establishes a
"regenerate and diff" pattern for committed artefacts, and any such gate on this
report would have flapped on every machine, reporting drift where there is none —
the same shape as #602, where a generator that could not run in CI made a gate
useless.

`bytes=` plus a truncated `sha256=` identifies the input reproducibly. Verified by
regenerating the report with the crosswalk's mtime deliberately altered: the
output was byte-identical.

Pure string tests over the committed header, so they run in the blocking gate
even though regenerating the report needs a local kg-microbe checkout.
"""

from __future__ import annotations

import pathlib
import re

import pytest

REPO = pathlib.Path(__file__).parent.parent
REPORT = REPO / "reports/gtdb_denominators.tsv"


@pytest.fixture(scope="module")
def header() -> str:
    if not REPORT.is_file():
        pytest.skip("reports/gtdb_denominators.tsv is not built in this checkout")
    return REPORT.read_text(encoding="utf-8").splitlines()[0]


def test_the_header_names_the_crosswalk_and_its_size(header):
    assert header.startswith("# mapping:")
    assert "NCBI2GTDB.tsv.gz" in header
    assert re.search(r"\bbytes=\d+", header), f"no byte count in {header!r}"


def test_the_header_carries_a_content_hash(header):
    """A hash is what makes the header reproducible across machines."""
    match = re.search(r"\bsha256=([0-9a-f]+)", header)
    assert match, f"no sha256 in {header!r}"
    assert len(match.group(1)) >= 8, "a hash this short does not identify a build"


def test_the_header_carries_no_mtime(header):
    """The gate. An mtime is a property of a filesystem, not of the data.

    Regenerating after `touch`-ing the crosswalk produced a byte-identical
    report once this held; before, line 1 changed and nothing else did.
    """
    assert "mtime=" not in header, (
        "the provenance header records a filesystem mtime again (#479). It "
        "differs per machine and per re-download even when the crosswalk's "
        "bytes are identical, so any regenerate-and-diff gate on this report "
        f"would flap: {header!r}"
    )


def test_the_producer_agrees_with_the_committed_header():
    """Guard against fixing the file and leaving the script writing mtime.

    The header could be hand-edited, or regenerated by an older copy of the
    script. Reading the source is what ties the artefact to its producer — the
    same reason #602 gates the published page against its template rather than
    trusting that a generator ran.
    """
    source = (REPO / "scripts/gtdb_denominator_compare.py").read_text(encoding="utf-8")
    start = source.find('f"# mapping:')
    assert start > 0, "could not find the code that writes the provenance header"
    # A window, not a line and not a delimiter search. The f-string is split
    # across two physical lines, so a line-at-a-time scan finds `bytes=` and
    # `sha256=` separately and concludes the hash is missing; and the closing
    # paren is indented, so searching for "\n)" raises. Both were real failures
    # of this test before it tested anything.
    writer = source[start : start + 300]
    assert "mtime" not in writer, f"the script still writes an mtime: {writer!r}"
    assert "sha256" in writer, f"the script does not write a content hash: {writer!r}"
